# given a list vcf file under the folder
vcf_input_dir: "/data/zhuw10/ukbb/data/genomel_vcf"

### output_dir is sufficient to keep data unique and output_prefix is to for the merged file
output_dir: "/data/GenoMEL/PLP_prediction_workflow/output"
output_prefix: "genomel"
ref: "/data/GenoMEL/AutoGVP/data/Homo_sapiens_assembly19.fasta"
genome: "hg19"
genome_GRC: "GRCh37"
clinvar:
  dir: "/data/GenoMEL/AutoGVP/data"
  vcf: "clinvar_20231230.vcf.gz"
  selected_submission: "ClinVar-selected-submissions.tsv"
  variant_summary: "variant_summary.txt.gz"
  submission_summary: "submission_summary.txt.gz"
conceptIDs: "/data/GenoMEL/AutoGVP/AutoGVP/data/clinvar_cpg_concept_ids.txt"
split_total: 100

